### ISSUE TITLE
Criação Pedidos

### ISSUE THREAD

**Issue by thallysfss** [bbarreto/skyhub-php-sdk#7]
Olá, estou utilizando o SDK, porém para homologar está pedindo para criar pedido, não encontrei esse método no SDK, ele existe? Caso contrário irei criar e contribuir com o projeto se for aceito...

Att,
Thallys

**Comment by bbarreto** [comment]
A criação de pedidos só é permitida no ambiente de homologação. A aplicação em produção nunca vai criar pedidos porque ele é criado diretamente pela B2W a partir das lojas onde o produto foi anunciado.

Não previ colocar isso na SDK exatamente porque só vai ser usado uma vez na homologação (e a chamada pode ser um POST direto do terminal via curl ou usando um app tipo postman), mas fique à vontade pra contribuir com o projeto. :)

**Comment by thallysfss** [comment]
Certo, entendi. Não havia me atentado para usar algum serviço para fazer o post. Vou usar um deles, mas se ver oportunidade de contribuir com o projeto, vou fazer.

Muito obrigado pelo feedback.
