### ISSUE TITLE
Erro na wiki

### ISSUE THREAD

**Issue by humbcezar** [bbarreto/skyhub-php-sdk#8]
Na página Variations, em Atualizar variação de um produto está escrito: 
$retorno = $skyhub->products()->**variations**->update('TESTEABC_VAR1', [
    "qty"=> 100,
    "ean"=> "9823093830285"
]);

Ao invés de:
$retorno = $skyhub->products()->**variations()**->update('TESTEABC_VAR1', [
    "qty"=> 100,
    "ean"=> "9823093830285"
]);

**Comment by bbarreto** [comment]
Corrigido
